// A220 Pro - acceso privado mediante Google/Supabase.
const A220_ALLOWED_EMAIL='kiosco.a220@gmail.com';
const A220_GOOGLE_KEY='a220_google_unlock_v1';
let isLoggedIn=false;
let a220AuthBooting=false;
let a220SessionFinishing=false;
function getSupabaseClient(){if(!window.supabase||typeof window.supabase.createClient!=='function')throw new Error('Supabase Auth no está disponible');if(!window.A220_SUPABASE)window.A220_SUPABASE=window.supabase.createClient(APP_CONFIG.supabaseUrl,APP_CONFIG.supabasePublishableKey);return window.A220_SUPABASE;}
async function doGoogleLogin(){const button=document.getElementById('googleLoginBtn'),error=document.getElementById('loginError');if(error)error.textContent='';if(button)button.disabled=true;try{const client=getSupabaseClient(),redirectTo=window.location.origin+window.location.pathname;const {error:e}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo,queryParams:{prompt:'select_account'}}});if(e)throw e;}catch(e){if(error)error.textContent='❌ '+(e?.message||'No se pudo iniciar sesión con Google');if(button)button.disabled=false;}}
async function finishGoogleSession(session){if(a220SessionFinishing)return false;a220SessionFinishing=true;try{const email=(session?.user?.email||'').toLowerCase();if(email!==A220_ALLOWED_EMAIL){await getSupabaseClient().auth.signOut();throw new Error('Esta cuenta no está autorizada para A220.');}isLoggedIn=true;await unlockDataWithGoogle();document.getElementById('loginOverlay')?.classList.add('hidden');renderAll();if(typeof bootstrapPrivateData==='function')await bootstrapPrivateData();renderAll();showToast('⚡ A220 lista','success');return true;}finally{a220SessionFinishing=false;}}
async function bootAuth(){if(a220AuthBooting)return;a220AuthBooting=true;try{const client=getSupabaseClient();client.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_IN'&&session){try{await finishGoogleSession(session)}catch(e){const el=document.getElementById('loginError');if(el)el.textContent='❌ '+e.message;}}if(event==='SIGNED_OUT'){isLoggedIn=false;}});const {data}=await client.auth.getSession();if(data?.session){await finishGoogleSession(data.session);return;}}catch(e){const el=document.getElementById('loginError');if(el)el.textContent='❌ '+(e?.message||'No se pudo inicializar el acceso');}finally{a220AuthBooting=false;}}
async function doLogout(){if(!confirm('¿Bloquear A220?'))return;isLoggedIn=false;a220Password='';a220Key=null;appData=null;try{await getSupabaseClient().auth.signOut()}catch(_e){}document.getElementById('loginOverlay')?.classList.remove('hidden');}