// A220 Pro - Google OAuth + acceso exclusivo
const A220_ALLOWED_EMAIL='kiosco.a220@gmail.com';
const A220_GOOGLE_KEY='a220_google_unlock_v1';
let isLoggedIn=false;
function getSupabaseClient(){if(!window.supabase||typeof window.supabase.createClient!=='function')throw new Error('Supabase Auth no está disponible');if(!window.A220_SUPABASE)window.A220_SUPABASE=window.supabase.createClient(APP_CONFIG.supabaseUrl,APP_CONFIG.supabasePublishableKey);return window.A220_SUPABASE;}
async function doGoogleLogin(){const button=document.getElementById('googleLoginBtn'),error=document.getElementById('loginError');error.textContent='';button.disabled=true;try{const client=getSupabaseClient(),redirectTo=window.location.origin+window.location.pathname;const {error:e}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo,queryParams:{prompt:'select_account'}}});if(e)throw e;}catch(e){error.textContent='❌ '+(e?.message||'No se pudo iniciar sesión con Google');button.disabled=false;}}
async function finishGoogleSession(session){const email=(session?.user?.email||'').toLowerCase();if(email!==A220_ALLOWED_EMAIL){await getSupabaseClient().auth.signOut();throw new Error('Esta cuenta no está autorizada para A220.');}await unlockDataWithGoogle();isLoggedIn=true;document.getElementById('loginOverlay').classList.add('hidden');renderAll();showToast('✅ A220 desbloqueada','success');}
async function bootAuth(){try{const client=getSupabaseClient(),{data}=await client.auth.getSession();if(data?.session){await finishGoogleSession(data.session);return;}client.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_IN'&&session){try{await finishGoogleSession(session)}catch(e){document.getElementById('loginError').textContent='❌ '+e.message;}}});}catch(e){document.getElementById('loginError').textContent='❌ '+(e?.message||'No se pudo inicializar el acceso');}}
async function doLogout(){if(!confirm('¿Bloquear A220?'))return;isLoggedIn=false;a220Password='';a220Key=null;appData=null;if(typeof clearSyncKey==='function')clearSyncKey();try{await getSupabaseClient().auth.signOut()}catch(_e){}document.getElementById('loginOverlay').classList.remove('hidden');}
document.addEventListener('DOMContentLoaded',bootAuth);