// A220 Pro - clientes
function getClientById(id){return (appData?.clients||[]).find(c=>c.id===Number(id))||null}
function clientKey(name,phone=''){return `${String(name||'').trim().toLowerCase()}|${String(phone||'').replace(/\D/g,'')}`}
function normalizeClient(c,i=0){return{id:Number(c?.id)||i+1,name:String(c?.name||'').trim(),phone:String(c?.phone||'').trim(),email:String(c?.email||'').trim(),notes:String(c?.notes||'').trim(),createdAt:c?.createdAt||new Date().toISOString(),updatedAt:c?.updatedAt||c?.createdAt||new Date().toISOString()}}
function renderClientDatalist(){const dl=document.getElementById('clientesDatalist');if(!dl)return;dl.innerHTML=(appData?.clients||[]).filter(c=>c.name).sort((a,b)=>a.name.localeCompare(b.name,'es')).map(c=>`<option value="${escapeHTML(c.name)}">${escapeHTML(c.phone||'')}</option>`).join('')}
function renderClients(){const tbody=document.getElementById('clientsTable');if(!tbody||!appData)return;const rows=[...(appData.clients||[])].filter(c=>c.name).sort((a,b)=>a.name.localeCompare(b.name,'es'));tbody.innerHTML=rows.map(c=>`<tr><td><strong>${escapeHTML(c.name)}</strong></td><td>${escapeHTML(c.phone||'—')}</td><td>${escapeHTML(c.email||'—')}</td><td>${escapeHTML(c.notes||'—')}</td><td><button class="btn btn-xs btn-outline" onclick="editClient(${c.id})">Editar</button> <button class="btn btn-xs btn-danger" onclick="deleteClient(${c.id})">×</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">No hay clientes guardados.</td></tr>';renderClientDatalist()}
function clearClientForm(){['clientId','clientName','clientPhone','clientEmail','clientNotes'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''});const t=document.getElementById('clientFormTitle');if(t)t.textContent='Nuevo cliente'}
function saveClient(){if(!appData)return false;const name=document.getElementById('clientName')?.value.trim();if(!name){showToast('⚠️ Ingresá el nombre del cliente','error');return false}const phone=document.getElementById('clientPhone')?.value.trim(),email=document.getElementById('clientEmail')?.value.trim(),notes=document.getElementById('clientNotes')?.value.trim(),id=Number(document.getElementById('clientId')?.value)||0,now=new Date().toISOString();appData.clients=Array.isArray(appData.clients)?appData.clients:[];const duplicate=appData.clients.find(c=>c.id!==id&&clientKey(c.name,c.phone)===clientKey(name,phone));if(duplicate){showToast('⚠️ Ese cliente ya está guardado','info');return false}if(id){const c=getClientById(id);if(c){Object.assign(c,{name,phone,email,notes,updatedAt:now})}}else appData.clients.push({id:nextId(appData.clients),name,phone,email,notes,createdAt:now,updatedAt:now});saveLocalData();renderClients();clearClientForm();showToast('✅ Cliente guardado','success');return true}
function editClient(id){const c=getClientById(id);if(!c)return;document.getElementById('clientId').value=c.id;document.getElementById('clientName').value=c.name;document.getElementById('clientPhone').value=c.phone||'';document.getElementById('clientEmail').value=c.email||'';document.getElementById('clientNotes').value=c.notes||'';document.getElementById('clientFormTitle').textContent='Editar cliente';document.getElementById('clientName').focus()}
function deleteClient(id){const c=getClientById(id);if(!c)return;if(!confirm(`¿Eliminar a ${c.name}?`))return;appData.clients=appData.clients.filter(x=>x.id!==id);saveLocalData();renderClients();showToast('Cliente eliminado','success')}
function saveCurrentSaleClient(){const name=document.getElementById('clienteNombre')?.value.trim();if(!name){showToast('⚠️ Escribí el nombre del cliente primero','error');return false}const phone=document.getElementById('clienteTelefono')?.value.trim()||'',email='',now=new Date().toISOString();appData.clients=Array.isArray(appData.clients)?appData.clients:[];let c=appData.clients.find(x=>clientKey(x.name,x.phone)===clientKey(name,phone))||appData.clients.find(x=>x.name.toLowerCase()===name.toLowerCase());if(c){c.phone=phone||c.phone;c.updatedAt=now}else{c={id:nextId(appData.clients),name,phone,email,notes:'',createdAt:now,updatedAt:now};appData.clients.push(c)}saveLocalData();renderClients();renderClientDatalist();showToast('👤 Cliente guardado','success');return true}
function selectSavedClient(name){const c=(appData?.clients||[]).find(x=>x.name.toLowerCase()===String(name||'').trim().toLowerCase());if(c){const phone=document.getElementById('clienteTelefono');if(phone&&!phone.value)phone.value=c.phone||'';const input=document.getElementById('clienteNombre');if(input)input.dataset.clientId=c.id}else{const input=document.getElementById('clienteNombre');if(input)delete input.dataset.clientId}}
