// A220 Pro - clientes
function getClientById(id){return (appData?.clients||[]).find(c=>c.id===Number(id))||null}
function clientKey(name,phone=''){return `${String(name||'').trim().toLowerCase()}|${String(phone||'').replace(/\D/g,'')}`}
function normalizeClient(c,i=0){return{id:Number(c?.id)||i+1,name:String(c?.name||'').trim(),phone:String(c?.phone||'').trim(),email:String(c?.email||'').trim(),notes:String(c?.notes||'').trim(),createdAt:c?.createdAt||new Date().toISOString(),updatedAt:c?.updatedAt||c?.createdAt||new Date().toISOString()}}
function renderClientDatalist(){const dl=document.getElementById('clientesDatalist');if(!dl)return;dl.innerHTML=(appData?.clients||[]).filter(c=>c.name).sort((a,b)=>a.name.localeCompare(b.name,'es')).map(c=>`<option value="${escapeHTML(c.name)}">${escapeHTML(c.phone||'')}</option>`).join('')}
function renderClientStats(){const box=document.getElementById('clientStats');if(!box||!appData)return;const clients=appData.clients||[],sales=appData.sales||[],linked=sales.filter(s=>s.clientId||String(s.cliente||'').trim()&&String(s.cliente).toLowerCase()!=='sin cliente'),total=linked.reduce((n,s)=>n+Number(s.total||0),0);box.innerHTML=`<div class="cards"><div class="card"><span>👤</span><div>Clientes<strong>${clients.length}</strong></div></div><div class="card"><span>🧾</span><div>Ventas con cliente<strong>${linked.length}</strong></div></div><div class="card"><span>💰</span><div>Facturación identificada<strong>${money(total)}</strong></div></div></div>`}
function renderClients(){const tbody=document.getElementById('clientsTable');if(!tbody||!appData)return;const rows=[...(appData.clients||[])].filter(c=>c.name).sort((a,b)=>a.name.localeCompare(b.name,'es'));tbody.innerHTML=rows.map(c=>`<tr><td><strong>${escapeHTML(c.name)}</strong></td><td>${escapeHTML(c.phone||'—')}</td><td>${escapeHTML(c.email||'—')}</td><td>${escapeHTML(c.notes||'—')}</td><td><button class="btn btn-xs btn-outline" onclick="editClient(${c.id})">Editar</button> <button class="btn btn-xs btn-danger" onclick="deleteClient(${c.id})">×</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">No hay clientes guardados.</td></tr>';renderClientDatalist();renderClientStats()}
function clearClientForm(){['clientId','clientName','clientPhone','clientEmail','clientNotes'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''});const t=document.getElementById('clientFormTitle');if(t)t.textContent='Nuevo cliente'}
function saveClient(){if(!appData)return false;const name=document.getElementById('clientName')?.value.trim();if(!name){showToast('⚠️ Ingresá el nombre del cliente','error');return false}const phone=document.getElementById('clientPhone')?.value.trim(),email=document.getElementById('clientEmail')?.value.trim(),notes=document.getElementById('clientNotes')?.value.trim(),id=Number(document.getElementById('clientId')?.value)||0,now=new Date().toISOString();appData.clients=Array.isArray(appData.clients)?appData.clients:[];const duplicate=appData.clients.find(c=>c.id!==id&&clientKey(c.name,c.phone)===clientKey(name,phone));if(duplicate){showToast('⚠️ Ese cliente ya está guardado','info');return false}if(id){const c=getClientById(id);if(c)Object.assign(c,{name,phone,email,notes,updatedAt:now})}else appData.clients.push({id:nextId(appData.clients),name,phone,email,notes,createdAt:now,updatedAt:now});saveLocalData();renderClients();clearClientForm();showToast('✅ Cliente guardado','success');return true}
function editClient(id){const c=getClientById(id);if(!c)return;document.getElementById('clientId').value=c.id;document.getElementById('clientName').value=c.name;document.getElementById('clientPhone').value=c.phone||'';document.getElementById('clientEmail').value=c.email||'';document.getElementById('clientNotes').value=c.notes||'';document.getElementById('clientFormTitle').textContent='Editar cliente';document.getElementById('clientName').focus()}
function deleteClient(id){const c=getClientById(id);if(!c)return;if(!confirm(`¿Eliminar a ${c.name}?`))return;appData.clients=appData.clients.filter(x=>x.id!==id);saveLocalData();renderClients();showToast('Cliente eliminado','success')}
function saveCurrentSaleClient(){const name=document.getElementById('clienteNombre')?.value.trim();if(!name){showToast('⚠️ Escribí el nombre del cliente primero','error');return false}const phone=document.getElementById('clienteTelefono')?.value.trim()||'',now=new Date().toISOString();appData.clients=Array.isArray(appData.clients)?appData.clients:[];let c=appData.clients.find(x=>clientKey(x.name,x.phone)===clientKey(name,phone))||appData.clients.find(x=>x.name.toLowerCase()===name.toLowerCase());if(c){c.phone=phone||c.phone;c.updatedAt=now}else{c={id:nextId(appData.clients),name,phone,email:'',notes:'',createdAt:now,updatedAt:now};appData.clients.push(c)}const input=document.getElementById('clienteNombre');if(input)input.dataset.clientId=c.id;saveLocalData();renderClients();showToast('👤 Cliente guardado','success');return true}
function selectSavedClient(name){const c=(appData?.clients||[]).find(x=>x.name.toLowerCase()===String(name||'').trim().toLowerCase()),input=document.getElementById('clienteNombre');if(c){const phone=document.getElementById('clienteTelefono');if(phone&&!phone.value)phone.value=c.phone||'';if(input)input.dataset.clientId=c.id}else if(input)delete input.dataset.clientId}
function initA220ClientsUI(){if(!document.querySelector('nav button[data-a220-clients]')){const nav=document.querySelector('nav');const b=document.createElement('button');b.dataset.a220Clients='1';b.textContent='👤 Clientes';b.onclick=()=>showView('clientes',b);nav?.insertBefore(b,nav.lastElementChild)}if(!document.getElementById('clientes')){const sec=document.createElement('section');sec.id='clientes';sec.className='view';sec.innerHTML='<div class="page-head"><div><div class="eyebrow">RELACIÓN</div><h2>Clientes</h2></div><button class="btn btn-outline" onclick="clearClientForm()">Nuevo</button></div><div id="clientStats"></div><div class="panel"><h3 id="clientFormTitle">Nuevo cliente</h3><input type="hidden" id="clientId"><div class="grid2"><input id="clientName" placeholder="Nombre"><input id="clientPhone" placeholder="Teléfono"><input id="clientEmail" type="email" placeholder="Email"><input id="clientNotes" placeholder="Notas"></div><button class="btn btn-primary" onclick="saveClient()">Guardar cliente</button> <button class="btn btn-outline" onclick="clearClientForm()">Limpiar</button></div><div class="panel"><h3>Clientes guardados</h3><div class="muted">Los clientes se sincronizan junto con las ventas y quedan disponibles para estadísticas.</div><div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Teléfono</th><th>Email</th><th>Notas</th><th></th></tr></thead><tbody id="clientsTable"></tbody></table></div></div>';document.querySelector('main')?.appendChild(sec)}const name=document.getElementById('clienteNombre');if(name&&!name.dataset.a220ClientBound){name.dataset.a220ClientBound='1';name.setAttribute('list','clientesDatalist');name.addEventListener('change',()=>selectSavedClient(name.value));name.insertAdjacentHTML('afterend','<datalist id="clientesDatalist"></datalist>')}renderClients()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initA220ClientsUI);else initA220ClientsUI();
