// A220 Pro v5 - cifrado local. La sesión de Supabase identifica al usuario; no hay clave manual de sincronización.
let a220Key=null,a220Password='';
const A220_ENVELOPE='A220-ENCRYPTED-JSON',enc=new TextEncoder(),dec=new TextDecoder();
function bytesToB64(bytes){let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}
function b64ToBytes(s){const b=atob(s);return Uint8Array.from(b,c=>c.charCodeAt(0));}
async function deriveA220Key(password,salt){const m=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},m,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function createEnvelope(data,password){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await deriveA220Key(password,salt),clean=JSON.parse(JSON.stringify(normalizeData(data)));const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(clean)));return {format:A220_ENVELOPE,version:1,kdf:'PBKDF2-SHA256-310000',cipher:'AES-256-GCM',salt:bytesToB64(salt),iv:bytesToB64(iv),ciphertext:bytesToB64(new Uint8Array(ciphertext)),revision:Number(clean.revision)||0,updatedAt:clean.updatedAt||new Date().toISOString()};}
async function decryptEnvelope(env,password){if(!env||env.format!==A220_ENVELOPE)throw new Error('Formato A220 no válido');const key=await deriveA220Key(password,b64ToBytes(env.salt)),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(env.iv)},key,b64ToBytes(env.ciphertext));return {data:normalizeData(JSON.parse(dec.decode(plain))),key};}
function initialA220Data(){return normalizeData({schemaVersion:5,products:[],sales:[],moves:[],scans:[],microframes:[],activities:[],revision:0,updatedAt:new Date().toISOString()});}
function getGoogleUnlockSecret(){return localStorage.getItem(A220_GOOGLE_KEY)||'';}
function createGoogleUnlockSecret(){return bytesToB64(crypto.getRandomValues(new Uint8Array(32)))+'-A220-V5';}
async function unlockDataWithGoogle(){let secret=getGoogleUnlockSecret();if(!secret){secret=createGoogleUnlockSecret();localStorage.setItem(A220_GOOGLE_KEY,secret);}a220Password=secret;const stored=localStorage.getItem(APP_CONFIG.storageKey);if(stored){try{const r=await decryptEnvelope(JSON.parse(stored),secret);appData=r.data;a220Key=r.key;return true}catch(e){console.warn('A220: almacenamiento local v5 inválido; se crea base limpia.',e)}}appData=initialA220Data();const env=await createEnvelope(appData,secret);localStorage.setItem(APP_CONFIG.storageKey,JSON.stringify(env));a220Key=await deriveA220Key(secret,b64ToBytes(env.salt));return true;}
async function persistEncrypted(render=true){if(!a220Key)throw new Error('A220 está bloqueada');appData=normalizeData(appData);appData.updatedAt=new Date().toISOString();appData.revision=Number(appData.revision||0)+1;const env=await createEnvelope(appData,a220Password);localStorage.setItem(APP_CONFIG.storageKey,JSON.stringify(env));if(render&&typeof renderAll==='function')renderAll();return env;}
let a220SyncTimer=null;
async function saveLocalData(render=true){try{const env=await persistEncrypted(render);clearTimeout(a220SyncTimer);a220SyncTimer=setTimeout(()=>{if(typeof syncToGitHub==='function')syncToGitHub().catch(e=>console.error('A220 autosync:',e))},900);return !!env}catch(e){showToast('❌ No se pudo guardar','error');return false}}
async function exportJSON(){try{const env=await createEnvelope(appData,a220Password);downloadText('a220-backup-latest.a220.json',JSON.stringify(env,null,2),'application/json');showToast('🔐 Último backup cifrado descargado','success')}catch(e){showToast('❌ No se pudo exportar','error')}}
function importJSON(file){if(!file)return;const r=new FileReader();r.onload=async()=>{try{const env=JSON.parse(r.result),x=await decryptEnvelope(env,a220Password);if(!confirm(`Restaurar ${x.data.products.length} productos y ${x.data.sales.length} ventas?`))return;localStorage.setItem(APP_CONFIG.storageKey+'_before_import',localStorage.getItem(APP_CONFIG.storageKey));appData=x.data;a220Key=x.key;await persistEncrypted(false);renderAll();showToast('✅ Backup restaurado','success')}catch(e){showToast('❌ Backup inválido','error')}};r.readAsText(file)}
