// A220 Pro - cifrado AES-256-GCM + PBKDF2
let a220Key=null,a220Password=''; const A220_ENVELOPE='A220-ENCRYPTED-JSON'; const enc=new TextEncoder(),dec=new TextDecoder();
function bytesToB64(bytes){let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)} function b64ToBytes(s){const b=atob(s);return Uint8Array.from(b,c=>c.charCodeAt(0));}
async function deriveA220Key(password,salt){const m=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},m,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function createEnvelope(data,password){const salt=crypto.getRandomValues(new Uint8Array(16)),key=await deriveA220Key(password,salt),iv=crypto.getRandomValues(new Uint8Array(12)),clean=JSON.parse(JSON.stringify(data));delete clean.__salt;const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(clean)));return {format:A220_ENVELOPE,version:1,kdf:'PBKDF2-SHA256-310000',cipher:'AES-256-GCM',salt:bytesToB64(salt),iv:bytesToB64(iv),ciphertext:bytesToB64(new Uint8Array(cipher)),revision:Number(clean.revision)||0,updatedAt:clean.updatedAt||new Date().toISOString()};}
async function decryptEnvelope(env,password){if(!env||env.format!==A220_ENVELOPE)throw new Error('Formato A220 cifrado no válido');const key=await deriveA220Key(password,b64ToBytes(env.salt)),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(env.iv)},key,b64ToBytes(env.ciphertext));return {data:normalizeData(JSON.parse(dec.decode(plain))),key};}
async function setSessionPassword(p){a220Password=p;} async function getPasswordKey(){const env=JSON.parse(localStorage.getItem(APP_CONFIG.storageKey));return deriveA220Key(a220Password,b64ToBytes(env.salt));}
function initialA220Data(){let d=typeof getDefaultProducts==='function'?getDefaultProducts():[];if(!Array.isArray(d)||!d.length)d=[{id:1,name:'Cigarrillos Red Point ON Convertible x20',cat:'Cigarrillos',cost:0,price:2700,stock:10,minStock:0,barcode:'77959751',image:'',brand:'Red Point',quantity:'x20',source:'A220',sourceUrl:'',priceReference:2700,priceOrigin:'reference'}];return {products:d,sales:[],moves:[],revision:0,updatedAt:new Date().toISOString()};}
async function unlockData(password){const stored=localStorage.getItem(APP_CONFIG.storageKey);if(!stored){appData=normalizeData(initialA220Data());const env=await createEnvelope(appData,password);localStorage.setItem(APP_CONFIG.storageKey,JSON.stringify(env));a220Key=await deriveA220Key(password,b64ToBytes(env.salt));return true;}try{const r=await decryptEnvelope(JSON.parse(stored),password);appData=r.data;if(!Array.isArray(appData.products))appData.products=[];if(appData.products.length===0){const seed=initialA220Data().products;if(seed.length){appData.products=seed;const env=await createEnvelope(appData,password);localStorage.setItem(APP_CONFIG.storageKey,JSON.stringify(env));a220Key=await deriveA220Key(password,b64ToBytes(env.salt));return true;}}a220Key=r.key;return true}catch(e){a220Key=null;throw new Error('Contraseña incorrecta o datos cifrados dañados');}}
async function persistEncrypted(render=true){if(!a220Key)throw new Error('La aplicación está bloqueada');appData.updatedAt=new Date().toISOString();appData.revision=Number(appData.revision||0)+1;const env=await createEnvelope(appData,a220Password);localStorage.setItem(APP_CONFIG.storageKey,JSON.stringify(env));if(render&&typeof renderAll==='function')renderAll();return env;}
async function saveLocalData(render=true){try{await persistEncrypted(render);return true}catch(e){showToast('❌ No se pudo guardar de forma cifrada','error');return false}}
async function exportJSON(){try{const env=await createEnvelope(appData,a220Password);downloadText(`a220-backup-${new Date().toISOString().slice(0,10)}.a220.json`,JSON.stringify(env,null,2),'application/json');showToast('🔐 Backup cifrado descargado','success')}catch(e){showToast('❌ No se pudo exportar','error')}}
function importJSON(file){if(!file)return;const r=new FileReader();r.onload=async()=>{try{const env=JSON.parse(r.result),x=await decryptEnvelope(env,a220Password);if(!confirm(`Restaurar ${x.data.products.length} productos y ${x.data.sales.length} ventas?`))return;localStorage.setItem(APP_CONFIG.storageKey+'_before_import',localStorage.getItem(APP_CONFIG.storageKey));appData=x.data;a220Key=x.key;await persistEncrypted(false);renderAll();showToast('✅ Backup restaurado','success')}catch(e){showToast('❌ Backup inválido o contraseña incorrecta','error')}};r.readAsText(file)}
function getGoogleUnlockSecret(){return localStorage.getItem(A220_GOOGLE_KEY)||'';}
function createGoogleUnlockSecret(){return bytesToB64(crypto.getRandomValues(new Uint8Array(32)))+'-A220-GOOGLE';}
async function unlockDataWithGoogle(){let secret=getGoogleUnlockSecret(),stored=localStorage.getItem(APP_CONFIG.storageKey);if(secret){await unlockData(secret);return true;}const old=prompt(stored?'Primer acceso con Google. Para migrar tus datos cifrados, ingresá una única vez la contraseña anterior de A220.':'Primer acceso en este navegador. Ingresá la contraseña anterior de A220 para intentar recuperar la copia sincronizada.');if(!old)throw new Error('Se necesita la contraseña anterior para recuperar tus datos.');if(stored){await unlockData(old);secret=createGoogleUnlockSecret();a220Password=secret;await persistEncrypted(false);localStorage.setItem(A220_GOOGLE_KEY,secret);return true;}if(typeof apiKey==='string'&&!apiKey){const syncKey=prompt('Ingresá la clave de sincronización de A220 para recuperar tus datos de la nube.');if(syncKey){apiKey=syncKey;try{sessionStorage.setItem(A220_SYNC_SESSION_KEY,apiKey)}catch(_){}}}if(typeof apiKey!=='string'||!apiKey)throw new Error('No hay una clave de sincronización para recuperar la copia de la nube.');const remote=await apiRequest('/data');if(!remote.exists||!remote.data)throw new Error('No existe una copia sincronizada en la nube.');const env=typeof remote.data==='string'?JSON.parse(remote.data):remote.data,x=await decryptEnvelope(env,old);if(!x.data.products.length&&!x.data.sales.length&&!x.data.moves.length)throw new Error('La copia de la nube está vacía; no se reemplazaron datos locales.');appData=x.data;secret=createGoogleUnlockSecret();a220Password=secret;await persistEncrypted(false);localStorage.setItem(A220_GOOGLE_KEY,secret);showToast(`☁️ ${appData.products.length} productos recuperados`,'success');return true;}
