// A220 Pro - sincronización privada por sesión Supabase.
const A220_API_URL='https://a220-api.kiosco-a220.workers.dev';
let apiKey='';
async function getAccessToken(){const client=typeof getSupabaseClient==='function'?getSupabaseClient():null;if(!client)throw new Error('Sesión de A220 no disponible');const {data,error}=await client.auth.getSession();if(error||!data?.session?.access_token)throw new Error('Sesión de A220 no disponible');return data.session.access_token;}
function loadGitHubConfig(){for(const id of ['githubUser','githubRepo','githubBranch','githubFile','apiKey','githubToken']){const el=document.getElementById(id);if(el)el.closest('.panel')?.querySelector(`#${id}`)?.remove?.();if(el)el.style.display='none';}const p=document.querySelector('#sync .panel:nth-of-type(2)');if(p){const old=p.querySelector('.legacy-sync-controls');if(old)old.remove();}apiKey='';}
function apiHeaders(token,extra={}){if(!token)throw new Error('Sesión de A220 no disponible');return{Authorization:`Bearer ${token}`,...extra};}
async function apiRequest(path,options={}){const token=await getAccessToken();const response=await fetch(`${A220_API_URL}${path}`,{...options,headers:{...apiHeaders(token,{'Content-Type':'application/json'}),...(options.headers||{})},cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||data.error||`API ${response.status}`);return data;}
async function lookupCatalog(barcode){const code=String(barcode||'').trim();if(!code)throw new Error('Código vacío');const local=appData?.products?.find(p=>String(p.barcode)===code);if(local)return{found:true,local:true,product:local};const response=await fetch(`${A220_API_URL}/catalog?barcode=${encodeURIComponent(code)}`,{cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Catálogo ${response.status}`);return data;}
async function lookupCatalogByName(query){const q=String(query||'').trim();if(!q)return{found:false,products:[]};const response=await fetch(`${A220_API_URL}/catalog?q=${encodeURIComponent(q)}`,{cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Catálogo ${response.status}`);return data;}
async function syncToGitHub(){if(!isLoggedIn)return;try{showToast('📤 Sincronizando...','info');const current=await apiRequest('/data');const localRev=Number(appData?.revision||0),remoteEnv=current?.data?(typeof current.data==='string'?JSON.parse(current.data):current.data):null,remoteRev=Number(remoteEnv?.revision||0);if(remoteRev>localRev){showToast(`☁️ La nube tiene una versión más nueva (rev ${remoteRev}). Se descargará primero.`,'info');await syncFromGitHub();return;}const env=await createEnvelope(appData,await getGoogleUnlockSecret());const result=await apiRequest('/data',{method:'PUT',body:JSON.stringify({data:env})});if(!result.ok)throw new Error(result.message||'No se pudo guardar');showToast('✅ Sincronizado','success');}catch(e){showToast('❌ '+e.message,'error');}}
async function syncFromGitHub(){if(!isLoggedIn)return;try{showToast('📥 Consultando datos...','info');const remote=await apiRequest('/data');if(!remote.exists||!remote.data){appData=normalizeData({products:[],sales:[],moves:[],scans:[],revision:0});await saveLocalData(false);renderAll();showToast('☁️ Base nueva lista','success');return;}const env=typeof remote.data==='string'?JSON.parse(remote.data):remote.data;const password=getGoogleUnlockSecret();if(!password)throw new Error('Identidad local de A220 no inicializada');const decrypted=await decryptEnvelope(env,password);appData=decrypted.data;await saveLocalData(false);renderAll();showToast(`☁️ Datos cargados · rev ${appData.revision}`,'success');}catch(e){console.error('A220 sync:',e);showToast('❌ '+e.message,'error');}}
async function syncPrivateData(){return syncFromGitHub();}
