// A220 Pro - sincronización privada + catálogo automático mediante a220-api.
const A220_API_URL = 'https://a220-api.kiosco-a220.workers.dev';
const A220_SYNC_SESSION_KEY = 'a220_sync_api_key';
let apiKey = '';
function loadGitHubConfig(){for(const id of ['githubUser','githubRepo','githubBranch','githubFile']){const el=document.getElementById(id);if(el)el.style.display='none'}let input=document.getElementById('apiKey');if(!input)input=document.getElementById('githubToken');if(input){input.id='apiKey';input.placeholder='Clave de sincronización';input.type='password';input.autocomplete='off';input.style.display=''}try{apiKey=sessionStorage.getItem(A220_SYNC_SESSION_KEY)||''}catch(_){apiKey=''}const b=document.querySelector('#sync button[onclick="saveGitHubConfig()"]');if(b)b.textContent=apiKey?'Clave cargada ✓':'Cargar clave'}
async function saveGitHubConfig(){const input=document.getElementById('apiKey'),value=input?.value.trim()||'';if(!value){if(apiKey)showToast('✅ La clave ya está cargada en esta sesión','success');else showToast('⚠️ Ingresá la clave de sincronización','error');return}apiKey=value;try{sessionStorage.setItem(A220_SYNC_SESSION_KEY,apiKey)}catch(_){}if(input)input.value='';try{const response=await fetch(`${A220_API_URL}/data`,{headers:{Authorization:`Bearer ${apiKey}`},cache:'no-store'});if(response.status===401)throw new Error('Clave de sincronización incorrecta');if(!response.ok)throw new Error(`API ${response.status}`);showToast('☁️ Sincronización lista','success')}catch(e){apiKey='';try{sessionStorage.removeItem(A220_SYNC_SESSION_KEY)}catch(_){}showToast('⚠️ '+e.message,'error')}}
function apiHeaders(){if(!apiKey)throw new Error('Cargá la clave de sincronización una sola vez');return{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'}}
async function apiRequest(path,options={}){const response=await fetch(`${A220_API_URL}${path}`,{...options,headers:{...apiHeaders(),...(options.headers||{})},cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||data.error||`API ${response.status}`);return data}
async function lookupCatalog(barcode){const code=String(barcode||'').trim();if(!code)throw new Error('Código vacío');const local=appData?.products?.find(p=>String(p.barcode)===code);if(local)return{found:true,local:true,product:local};return apiRequest(`/catalog?barcode=${encodeURIComponent(code)}`)}
async function syncToGitHub(){if(!isLoggedIn)return;try{showToast('📤 Cifrando y subiendo...','info');const env=await createEnvelope(appData,a220Password),current=await apiRequest('/data');if(current.exists&&current.data){try{const remoteEnv=typeof current.data==='string'?JSON.parse(current.data):current.data,remote=await decryptEnvelope(remoteEnv,a220Password);if(Number(remote.data?.revision||0)>Number(appData.revision||0)&&!confirm('Hay una versión más nueva en la nube. ¿Querés reemplazarla con esta copia?'))return}catch(_){throw new Error('Los datos remotos no se pueden validar con esta contraseña')}}const result=await apiRequest('/data',{method:'PUT',body:JSON.stringify({data:env})});if(!result.ok)throw new Error(result.message||'No se pudo guardar');showToast('✅ Sincronizado correctamente','success')}catch(e){showToast('❌ '+e.message,'error')}}
async function syncFromGitHub(){if(!isLoggedIn)return;try{showToast('📥 Descargando...','info');const remote=await apiRequest('/data');if(!remote.exists||!remote.data){showToast('⚠️ Todavía no existe una copia remota. Primero hacé una subida.','error');return}const env=typeof remote.data==='string'?JSON.parse(remote.data):remote.data,decrypted=await decryptEnvelope(env,a220Password),products=decrypted.data?.products?.length||0,sales=decrypted.data?.sales?.length||0;if(!confirm(`Restaurar la copia remota (rev ${decrypted.data.revision||0}, ${products} artículos, ${sales} ventas) y reemplazar la local?`))return;localStorage.setItem(APP_CONFIG.storageKey+'_before_sync',localStorage.getItem(APP_CONFIG.storageKey));appData=decrypted.data;await persistEncrypted(false);renderAll();showToast('✅ Datos restaurados desde la nube','success')}catch(e){showToast('❌ '+e.message,'error')}}
