// A220 Pro v5 - sincronización privada automática por sesión Supabase.
const A220_API_URL='https://a220-api.kiosco-a220.workers.dev';
let apiKey='';
async function getAccessToken(){const client=typeof getSupabaseClient==='function'?getSupabaseClient():null;if(!client)throw new Error('Sesión de A220 no disponible');const {data,error}=await client.auth.getSession();if(error||!data?.session?.access_token)throw new Error('Sesión de A220 no disponible');return data.session.access_token;}
function loadGitHubConfig(){for(const id of ['githubUser','githubRepo','githubBranch','githubFile','apiKey','githubToken']){const el=document.getElementById(id);if(el)el.style.display='none';}apiKey='';document.querySelectorAll('#sync button').forEach(b=>{if(/saveGitHubConfig|syncToGitHub|syncFromGitHub/.test(b.getAttribute('onclick')||''))b.style.display='none';});const p=document.querySelector('#sync .panel:nth-of-type(2) p');if(p)p.textContent='La sincronización es automática y privada. A220 usa tu sesión de Google para proteger tus datos.';}
function apiHeaders(token,extra={}){if(!token)throw new Error('Sesión de A220 no disponible');return{Authorization:`Bearer ${token}`,...extra};}
async function apiRequest(path,options={}){const token=await getAccessToken();const response=await fetch(`${A220_API_URL}${path}`,{...options,headers:{...apiHeaders(token,{'Content-Type':'application/json'}),...(options.headers||{})},cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||data.error||`API ${response.status}`);return data;}
async function lookupCatalog(barcode){const code=String(barcode||'').trim();if(!code)throw new Error('Código vacío');const local=appData?.products?.find(p=>String(p.barcode)===code);if(local)return{found:true,local:true,product:local};const response=await fetch(`${A220_API_URL}/catalog?barcode=${encodeURIComponent(code)}`,{cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Catálogo ${response.status}`);return data;}
async function lookupCatalogByName(query){const q=String(query||'').trim();if(!q)return{found:false,products:[]};const response=await fetch(`${A220_API_URL}/catalog?q=${encodeURIComponent(q)}`,{cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Catálogo ${response.status}`);return data;}
async function saveRemoteEnvelope(env){return apiRequest('/data',{method:'PUT',body:JSON.stringify({data:env})});}
async function syncToGitHub(){if(!isLoggedIn)return false;try{const current=await apiRequest('/data');const remoteEnv=current?.data?(typeof current.data==='string'?JSON.parse(current.data):current.data):null;const localRev=Number(appData?.revision||0),remoteRev=Number(remoteEnv?.revision||0);if(remoteEnv&&remoteRev>localRev){await syncFromGitHub();return true;}const env=await createEnvelope(appData,a220Password);await saveRemoteEnvelope(env);return true;}catch(e){console.error('A220 sync up:',e);showToast('⚠️ Sincronización pendiente','error');return false;}}
async function syncFromGitHub(){if(!isLoggedIn)return false;try{const remote=await apiRequest('/data');if(!remote.exists||!remote.data){await saveRemoteEnvelope(await createEnvelope(appData,a220Password));return true;}const env=typeof remote.data==='string'?JSON.parse(remote.data):remote.data;const localRev=Number(appData?.revision||0),remoteRev=Number(env?.revision||0);if(remoteRev<=localRev)return true;const decrypted=await decryptEnvelope(env,a220Password);appData=decrypted.data;const local=await createEnvelope(appData,a220Password);localStorage.setItem(APP_CONFIG.storageKey,JSON.stringify(local));a220Key=decrypted.key;renderAll();showToast(`☁️ Datos actualizados · rev ${remoteRev}`,'success');return true;}catch(e){console.error('A220 sync down:',e);return false;}}
async function bootstrapPrivateData(){if(!isLoggedIn)return false;try{const remote=await apiRequest('/data');if(!remote.exists||!remote.data){await saveRemoteEnvelope(await createEnvelope(appData,a220Password));showToast('☁️ Espacio privado creado','success');return true;}const env=typeof remote.data==='string'?JSON.parse(remote.data):remote.data;try{const decrypted=await decryptEnvelope(env,a220Password);appData=decrypted.data;const local=await createEnvelope(appData,a220Password);localStorage.setItem(APP_CONFIG.storageKey,JSON.stringify(local));a220Key=decrypted.key;renderAll();showToast(`☁️ Datos privados cargados · rev ${appData.revision}`,'success');return true;}catch(_){await saveRemoteEnvelope(await createEnvelope(appData,a220Password));showToast('☁️ Base privada reiniciada y limpia','success');return true;}}catch(e){console.error('A220 bootstrap:',e);showToast('⚠️ Trabajando en modo local; se reintentará la sincronización','error');return false;}}
async function syncPrivateData(){return bootstrapPrivateData();}
