// A220 Pro - puente de impresión térmica y cajón mediante QZ Tray
const A220_PRINTER_CONFIG={name:'TP-POS58',paperWidth:58,autoPrint:true,openDrawerOnCash:true};
function a220PrinterAvailable(){return typeof qz!=='undefined'&&!!qz.websocket}
async function a220ConnectPrinter(){if(!a220PrinterAvailable())throw new Error('QZ Tray no está instalado o disponible');if(!qz.websocket.isActive())await qz.websocket.connect();const found=await qz.printers.find(A220_PRINTER_CONFIG.name);const name=Array.isArray(found)?found[0]:found;if(!name)throw new Error('No se encontró la TP-POS58');return name}
function a220EscPosText(value){return String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/€/g,'EUR')}
function a220PrinterConfig(name){return qz.configs.create(name,{encoding:'CP850'})}
async function a220PrintRaw(data,printerName){const name=printerName||await a220ConnectPrinter();return qz.print(a220PrinterConfig(name),[{type:'raw',format:'command',flavor:'plain',data}])}
async function a220OpenDrawer(){const name=await a220ConnectPrinter();const pulse='\x1B\x70\x00\x19\xFA';await a220PrintRaw([pulse],name);return true}
async function a220PrintTicketDirect(s){const name=await a220ConnectPrinter();const L=a220EscPosText;let out='\x1B\x40\x1B\x61\x01';out+='A220\x0A';out+='Kiosco\x0A';out+=L(new Date(s.date).toLocaleString('es-AR'))+'\x0A';out+='------------------------------\x0A';for(const i of (s.items||[])){out+=L(i.name)+'\x0A';out+=String(i.qty)+' x '+money(i.price)+' = '+money(i.total)+'\x0A';}out+='------------------------------\x0A';out+='TOTAL '+money(s.total)+'\x0A';out+='Pago: '+L(s.paymentMethod==='cash'?'EFECTIVO':s.paymentMethod==='card'?'TARJETA':s.paymentMethod==='transfer'?'TRANSFERENCIA':'OTRO')+'\x0A';if(Number(s.paid)>0){out+='Recibido: '+money(s.paid)+'\x0A';out+='Vuelto: '+money(s.change)+'\x0A';}out+='\x0AGracias por tu compra!\x0A\x0A\x0A';if(s.paymentMethod==='cash'&&A220_PRINTER_CONFIG.openDrawerOnCash)out+='\x1B\x70\x00\x19\xFA';out+='\x1D\x56\x00';await a220PrintRaw([out],name);return true}
async function a220PrintPurchaseDirect(items){const name=await a220ConnectPrinter();const L=a220EscPosText;let out='\x1B\x40\x1B\x61\x01LISTA DE COMPRA\x0A\x1B\x61\x00';out+='A220 · '+L(new Date().toLocaleString('es-AR'))+'\x0A';out+='------------------------------\x0A';for(const x of items){out+=L(x.p.name||'Producto')+'\x0A';out+=String(x.stock)+' +'+String(x.qty)+' ='+String(x.min)+'\x0A';}const total=items.reduce((n,x)=>n+x.total,0),missing=items.filter(x=>x.cost<=0).length;out+='------------------------------\x0A';out+='COMPRA EST. '+money(total)+'\x0A';if(missing)out+='FALTAN COSTOS: '+missing+'\x0A';out+='\x0A\x0A\x1D\x56\x00';await a220PrintRaw([out],name);return true}
async function a220TryDirectPrintTicket(s){try{if(!a220PrinterAvailable())return false;await a220PrintTicketDirect(s);showToast('🖨️ Ticket enviado a TP-POS58','success');return true}catch(e){console.warn('A220 impresión directa:',e);showToast('Impresora directa no disponible. Se abrirá impresión de Windows.','info');return false}}
