// A220 Pro - impresion termica 58 mm + TXT para lista de compra
const A220_PRINTER_CONFIG={name:'TP-POS58',paperWidth:58,autoPrint:true,openDrawerOnCash:true};
let a220QZLoadPromise=null;
function a220LoadQZ(){if(typeof qz!=='undefined')return Promise.resolve();if(a220QZLoadPromise)return a220QZLoadPromise;a220QZLoadPromise=new Promise((resolve,reject)=>{const existing=document.querySelector('script[data-a220-qz]');if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',()=>reject(new Error('No se pudo cargar QZ Tray')),{once:true});return}const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/qz-tray@2.2.6/qz-tray.js';s.dataset.a220Qz='1';s.onload=resolve;s.onerror=()=>reject(new Error('No se pudo cargar QZ Tray'));document.head.appendChild(s)});return a220QZLoadPromise}
a220LoadQZ().catch(e=>console.warn('A220 QZ:',e));
function a220PrinterAvailable(){return typeof qz!=='undefined'&&!!qz.websocket}
async function a220ConnectPrinter(){await a220LoadQZ();if(!a220PrinterAvailable())throw new Error('QZ Tray no esta disponible');if(!qz.websocket.isActive())await qz.websocket.connect();let name=null;try{const found=await qz.printers.find(A220_PRINTER_CONFIG.name);name=Array.isArray(found)?found[0]:found}catch(e){}if(!name){const all=await qz.printers.find();name=(all||[]).find(x=>/TP[- ]?POS|POS58|58MM|THERMAL|TERMICA/i.test(String(x)))||null}if(!name){const all=await qz.printers.find();name=(all||[])[0]||null}if(!name)throw new Error('No se encontro una impresora en QZ Tray');return name}
function a220EscPosText(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function a220PrinterConfig(name){return qz.configs.create(name,{encoding:'CP850',copies:1,jobName:'A220 Kiosco'})}
async function a220PrintRaw(data,printerName){const name=printerName||await a220ConnectPrinter();const raw=Array.isArray(data)?data.join(''):String(data);return qz.print(a220PrinterConfig(name),[{type:'raw',format:'command',flavor:'plain',data:raw}])}
function a220Cut(){return '\x1D\x56\x00'}
function a220Finish(){return '\x1B\x64\x02'+a220Cut()}
function a220Header(title){return '\x1B\x40\x1B\x61\x01\x1B\x21\x10A220 KIOSCO\x1B\x21\x00\x0A'+a220EscPosText(title)+'\x0A\x1B\x61\x00'}
function a220PaymentName(m){return m==='cash'?'EFECTIVO':m==='card'?'TARJETA':m==='transfer'?'TRANSFERENCIA':'OTRO'}
async function a220OpenDrawer(){const name=await a220ConnectPrinter();return a220PrintRaw('\x1B\x70\x00\x19\xFA',name)}
async function a220PrintTicketDirect(s){const name=await a220ConnectPrinter();let out=a220Header('COMPROBANTE DE VENTA');out+='--------------------------------\x0A';out+=a220EscPosText(new Date(s.date).toLocaleString('es-AR'))+'\x0A';for(const i of(s.items||[])){out+=a220EscPosText(i.name||'Producto')+'\x0A';out+=String(i.qty)+' x '+money(i.price)+'  '+money(i.total)+'\x0A'}out+='--------------------------------\x0A';out+='TOTAL '+money(s.total)+'\x0A';out+='PAGO  '+a220PaymentName(s.paymentMethod)+'\x0A';if(Number(s.paid)>0){out+='RECIBIDO '+money(s.paid)+'\x0A';out+='VUELTO   '+money(s.change)+'\x0A'}out+='--------------------------------\x0A\x1B\x61\x01GRACIAS POR SU COMPRA\x0A\x1B\x61\x00';if(s.paymentMethod==='cash'&&A220_PRINTER_CONFIG.openDrawerOnCash)out+='\x1B\x70\x00\x19\xFA';out+=a220Finish();await a220PrintRaw(out,name);return true}
function a220BuildPurchaseText(items){const date=new Date().toLocaleDateString('es-AR');const missing=items.filter(x=>x.cost<=0);const total=items.reduce((n,x)=>n+x.total,0);let text='A220 KIOSCO\nLISTA DE COMPRA\n'+date+'\n--------------------------------\n';if(!items.length){text+='STOCK COMPLETO\nNO HAY COMPRAS\n'}else{for(const x of items){const name=a220EscPosText(x.p.name||'Producto').slice(0,24);text+=name+'\n';text+='STOCK '+x.stock+'  +'+x.qty+'  -> '+x.min+'\n'}text+='--------------------------------\nTOTAL EST. '+money(total)+'\n';if(missing.length)text+='SIN PRECIO: '+missing.length+'\n'}text+='--------------------------------\nA220 KIOSCO\n';return text}
function a220DownloadTxt(text){const stamp=new Date().toISOString().replace(/[:.]/g,'-').slice(0,19);const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='A220_lista_compra_'+stamp+'.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
async function a220PrintPurchaseDirect(items){const name=await a220ConnectPrinter();const text=a220BuildPurchaseText(items);a220DownloadTxt(text);let out=a220Header('LISTA DE COMPRA');for(const x of items){out+=a220EscPosText(x.p.name||'Producto').slice(0,24)+'\x0A';out+='STOCK '+String(x.stock)+'  +'+String(x.qty)+' -> '+String(x.min)+'\x0A'}const total=items.reduce((n,x)=>n+x.total,0),missing=items.filter(x=>x.cost<=0).length;out+='--------------------------------\x0A';out+='TOTAL EST. '+money(total)+'\x0A';if(missing)out+='SIN PRECIO: '+missing+'\x0A';out+='\x1B\x61\x01A220 KIOSCO\x0A\x1B\x61\x00';out+=a220Finish();await a220PrintRaw(out,name);return true}
async function a220TryDirectPrintTicket(s){try{await a220PrintTicketDirect(s);showToast('Ticket impreso','success');return true}catch(e){console.error('A220 print:',e);showToast('No se pudo imprimir: '+e.message,'error');return false}}

// Logo A220: rayo del favicon en bitmap ESC/POS + nombre del kiosco.
function a220LogoBitmap(){const d=[0,0,0,0,0,0,0,1,0,0,3,0,0,3,0,0,7,0,0,15,0,0,30,0,0,30,0,0,62,0,0,126,0,0,254,0,0,255,252,1,255,248,3,255,248,7,255,240,7,255,224,15,255,192,0,31,192,0,31,128,0,63,0,0,62,0,0,62,0,0,60,0,0,120,0,0,120,0,0,112,0,0,96,0,0,192,0,0,192,0,0,128,0,0,0,0];return String.fromCharCode(0x1d,0x76,0x30,0x00,0x03,0x00,0x20,0x00,...d)}
function a220Header(title){return '\x1B\x40\x1B\x61\x01'+a220LogoBitmap()+'\x0A\x1B\x21\x30A 220\x1B\x21\x00\x0A\x1B\x45\x01KIOSCO\x1B\x45\x00\x0A'+a220EscPosText(title)+'\x0A\x1B\x61\x00'}
