// A220 Pro - artículos y costos
let selectedProductId=null;
function productSourceLabel(p){const source=p.source||'A220';return source==='Open Food Facts'?'<span class="tag tag-source">Datos externos</span>':'<span class="tag tag-local">A220</span>'}
function priceOriginLabel(p){return p.priceOrigin==='manual'?'<span class="tag tag-manual">Modificado por vos</span>':'<span class="tag tag-price">Precio A220</span>'}
function renderProducts(){const tbody=document.getElementById('productsTable');if(!tbody||!appData)return;const q=(document.getElementById('productFilter')?.value||'').toLowerCase().trim(),rows=appData.products.filter(p=>!q||`${p.name} ${p.cat} ${p.barcode} ${p.brand}`.toLowerCase().includes(q));tbody.innerHTML=rows.map(p=>`<tr><td><strong>${escapeHTML(p.name)}</strong><div class="muted">${escapeHTML(p.brand||'')}</div></td><td>${escapeHTML(p.cat)}</td><td>${money(p.cost)}</td><td><strong>${money(p.price)}</strong><div>${priceOriginLabel(p)}</div></td><td class="${p.stock<=p.minStock?'stock-low':'stock-ok'}">${p.stock}</td><td>${escapeHTML(p.barcode||'—')}</td><td>${productSourceLabel(p)} <button class="btn btn-xs btn-outline" onclick="editProduct(${p.id})">Editar</button> <button class="btn btn-xs btn-danger" onclick="deleteProduct(${p.id})">Borrar</button></td></tr>`).join('')||'<tr><td colspan="7">No hay artículos.</td></tr>'}
function clearProductForm(){selectedProductId=null;['pName','pCat','pCost','pPrice','pStock','pMinStock','pBarcode'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''});document.getElementById('pCat').value='General';document.getElementById('pStock').value='0';document.getElementById('pMinStock').value='0';document.getElementById('pSourceInfo').textContent='Carga manual';document.getElementById('productFormTitle').textContent='Nuevo artículo'}
function saveProduct(){const name=document.getElementById('pName').value.trim();if(!name){showToast('⚠️ El nombre es obligatorio','error');return}const old=selectedProductId?appData.products.find(x=>x.id===selectedProductId):null,payload={name,cat:document.getElementById('pCat').value.trim()||'General',cost:Number(document.getElementById('pCost').value)||0,price:Number(document.getElementById('pPrice').value)||0,stock:Math.max(0,Number(document.getElementById('pStock').value)||0),minStock:Math.max(0,Number(document.getElementById('pMinStock').value)||0),barcode:document.getElementById('pBarcode').value.trim(),image:old?.image||'',brand:old?.brand||'',quantity:old?.quantity||'',source:old?.source||'A220',sourceUrl:old?.sourceUrl||'',priceOrigin:'manual'};if(selectedProductId){const p=appData.products.find(x=>x.id===selectedProductId);if(!p)return;Object.assign(p,payload)}else{payload.id=nextId(appData.products);appData.products.push(payload)}saveLocalData();clearProductForm();showToast('✅ Artículo guardado','success')}
function editProduct(id){const p=appData.products.find(x=>x.id===id);if(!p)return;selectedProductId=id;document.getElementById('pName').value=p.name;document.getElementById('pCat').value=p.cat;document.getElementById('pCost').value=p.cost;document.getElementById('pPrice').value=p.price;document.getElementById('pStock').value=p.stock;document.getElementById('pMinStock').value=p.minStock;document.getElementById('pBarcode').value=p.barcode;document.getElementById('pSourceInfo').textContent=(p.source||'A220')+(p.sourceUrl?' · catálogo externo':'');document.getElementById('productFormTitle').textContent='Editar artículo';showView('productos');window.scrollTo({top:0,behavior:'smooth'})}
function deleteProduct(id){const p=appData.products.find(x=>x.id===id);if(!p)return;if(!confirm(`¿Borrar "${p.name}"? Las ventas históricas no se borran.`))return;appData.products=appData.products.filter(x=>x.id!==id);saveLocalData();showToast('🗑️ Artículo eliminado','success')}
