// A220 Pro - ventas + ofertas
let cart=[],currentQty=1;
function findProduct(id){return appData.products.find(p=>p.id===Number(id))}
function productSearchText(p){return `${p.name||''} ${p.brand||''} ${p.cat||''} ${p.barcode||''}`.toLowerCase()}
function lockSalePrice(){const price=document.getElementById('salePrice');if(price){price.readOnly=true;price.setAttribute('readonly','readonly');price.title='El precio se modifica únicamente desde Artículos'}}
function renderSaleProducts(){const select=document.getElementById('saleProduct');if(!select||!appData)return;const current=select.value;const sorted=[...appData.products].filter(p=>Number(p.stock)>0).sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'es',{sensitivity:'base'}));select.innerHTML='<option value="">Seleccioná...</option>'+sorted.map(p=>`<option value="${p.id}">${escapeHTML(p.name)}${p.brand?` · ${escapeHTML(p.brand)}`:''} · ${money(p.price)} · Stock ${p.stock}</option>`).join('');if(sorted.some(p=>String(p.id)===String(current)))select.value=current;updateSalePreview();lockSalePrice();if(typeof a220EnsureQuickOffers==='function')a220EnsureQuickOffers()}
function setSelectedProduct(id){const p=findProduct(id);if(!p)return false;if(Number(p.stock)<=0){showToast('⚠️ Artículo sin stock. Cargá stock desde Artículos.','error');return false}const select=document.getElementById('saleProduct');if(select)select.value=String(p.id);const price=document.getElementById('salePrice');if(price){price.value=p.price;price.readOnly=true;price.setAttribute('readonly','readonly')}updateSalePreview();return true}
function updateSalePreview(){const p=findProduct(document.getElementById('saleProduct')?.value),box=document.getElementById('productPreview');if(!box)return;if(!p){box.innerHTML='<div class="product-image"><i class="fas fa-box"></i></div><div class="product-info"><div class="product-name">Seleccioná un artículo</div><div class="muted">La compra aparecerá acá</div></div>';return}lockSalePrice();const src=String(p.image||'').trim(),img=src?`<img src="${escapeHTML(src)}" alt="">`:'<i class="fas fa-box"></i>';box.innerHTML=`<div class="product-image">${img}</div><div class="product-info"><div class="product-name">${escapeHTML(p.name)}</div><div class="muted">${escapeHTML(p.brand||p.cat||'')}</div><div class="product-price">${money(p.price)}</div><div class="product-stock">Stock disponible: ${p.stock}</div></div>`}
function renderSearchResults(found){const list=document.getElementById('listaProductos');if(!list)return;list.innerHTML=found.map(p=>`<button class="search-result" onclick="setSelectedProduct(${p.id});document.getElementById('buscarProducto').value='';document.getElementById('listaProductos').style.display='none';"><span><strong>${escapeHTML(p.name)}</strong>${p.brand?`<small>${escapeHTML(p.brand)}</small>`:''}<small>${escapeHTML(p.cat||'General')} · Stock ${p.stock}</small></span><span>${money(p.price)}</span></button>`).join('')||'<div class="empty">No hay artículos con stock.</div>';list.style.display='block'}
function filterSaleProducts(){const input=document.getElementById('buscarProducto'),list=document.getElementById('listaProductos');if(!input||!list||!appData)return;const q=input.value.toLowerCase().trim();if(!q){list.style.display='none';return}const found=appData.products.filter(p=>Number(p.stock)>0&&productSearchText(p).includes(q)).sort((a,b)=>{const aa=productSearchText(a),bb=productSearchText(b),sa=aa.startsWith(q)?0:aa.indexOf(q)>=0?1:2,sb=bb.startsWith(q)?0:bb.indexOf(q)>=0?1:2;return sa-sb||String(a.name).localeCompare(String(b.name),'es',{sensitivity:'base'})}).slice(0,20);renderSearchResults(found)}
function focusProductSearch(){const input=document.getElementById('buscarProducto');input?.focus();if(input?.value)filterSaleProducts()}
function adjustQty(delta){currentQty=Math.max(1,currentQty+delta);const display=document.getElementById('qtyDisplay'),input=document.getElementById('saleQty');if(display)display.textContent=currentQty;if(input)input.value=currentQty}
function syncSaleQty(){const input=document.getElementById('saleQty');let value=Math.floor(Number(input?.value)||1);if(value<1)value=1;currentQty=value;input.value=value;const display=document.getElementById('qtyDisplay');if(display)display.textContent=value}
function addProductToCart(p,qty=1,priceOverride=null){if(!p){showToast('⚠️ Artículo no encontrado','error');return false}const stock=Number(p.stock);qty=Math.max(1,Number(qty)||1);if(!Number.isFinite(stock)||stock<qty){showToast(`⚠️ Stock insuficiente: ${p.name} (disponible: ${Number.isFinite(stock)?stock:0})`,'error');return false}const price=Math.max(0,Number(p.price)||0),existing=cart.find(x=>x.id===p.id),newQty=(existing?.qty||0)+qty;if(newQty>stock){showToast(`⚠️ Stock insuficiente: ${p.name} (disponible: ${stock}, pedido: ${newQty})`,'error');return false}if(existing){existing.qty=newQty;existing.price=price;existing.total=newQty*price}else cart.push({id:p.id,name:p.name,qty,price,total:qty*price});renderCart();showToast('➕ Agregado','success');return true}
function addToCart(){const p=findProduct(document.getElementById('saleProduct')?.value);if(!p){showToast('⚠️ Elegí un artículo','error');return false}syncSaleQty();const qty=Number(document.getElementById('saleQty')?.value)||1;return addProductToCart(p,qty)}
function renderCart(){const el=document.getElementById('cart');if(!el)return;el.innerHTML=cart.map((i,n)=>`<tr><td>${escapeHTML(i.name)}</td><td>${i.qty}</td><td>${money(i.price)}</td><td>${money(i.total)}</td><td><button class="btn btn-xs btn-danger" onclick="removeCart(${n})">×</button></td></tr>`).join('')||'<tr><td colspan="5" class="cart-empty">🛒 Agregá artículos para comenzar</td></tr>';const total=typeof a220GetSaleTotal==='function'?a220GetSaleTotal():cart.reduce((a,i)=>a+i.total,0);document.getElementById('cartTotal').textContent=money(total);if(typeof a220RenderCartOffers==='function')a220RenderCartOffers()}
function removeCart(i){cart.splice(i,1);renderCart()}
function togglePaymentFields(){const method=document.getElementById('paymentMethod')?.value||'cash',box=document.getElementById('cashPaymentFields');if(box)box.style.display=method==='cash'?'block':'none';if(method!=='cash'){const paid=document.getElementById('pagoEfectivo');if(paid)paid.value='';const change=document.getElementById('vueltoDisplay');if(change)change.textContent='$0'}}
function calcularVuelto(){const paid=Number(document.getElementById('pagoEfectivo').value)||0,total=typeof a220GetSaleTotal==='function'?a220GetSaleTotal():cart.reduce((a,i)=>a+i.total,0);document.getElementById('vueltoDisplay').textContent=money(Math.max(0,paid-total))}
function finishSale(){if(!cart.length){showToast('⚠️ El carrito está vacío','error');return}for(const i of cart){const p=findProduct(i.id);if(!p||i.qty>p.stock){showToast(`❌ Stock insuficiente: ${i.name}`,'error');return}}const offerSummary=typeof a220OfferSummary==='function'?a220OfferSummary(cart):{combos:[],baseTotal:cart.reduce((a,i)=>a+i.total,0),finalTotal:cart.reduce((a,i)=>a+i.total,0)},total=offerSummary.finalTotal,now=new Date().toISOString(),cliente=document.getElementById('clienteNombre').value.trim()||'Sin cliente',telefono=document.getElementById('clienteTelefono').value.trim(),paymentMethod=document.getElementById('paymentMethod')?.value||'cash',paid=paymentMethod==='cash'?(Number(document.getElementById('pagoEfectivo').value)||0):total;if(paymentMethod==='cash'&&paid<total){showToast('⚠️ El efectivo recibido es menor al total','error');return}const clientInput=document.getElementById('clienteNombre'),clientId=Number(clientInput?.dataset.clientId)||0;const sale={id:crypto.randomUUID(),date:now,total,items:structuredClone(cart),offers:structuredClone(offerSummary.combos||[]),cliente,telefono,clientId:clientId||null,paid,change:Math.max(0,paid-total),paymentMethod};cart.forEach(i=>{const p=findProduct(i.id);p.stock-=i.qty;appData.moves.unshift({id:crypto.randomUUID(),date:now,product:i.name,productId:i.id,qty:i.qty,total:i.total,cliente,clientId:clientId||null,saleId:sale.id})});appData.sales.unshift(sale);logActivity('sale','Venta realizada',`${cart.length} artículo(s)${offerSummary.combos?.length?` · ${offerSummary.combos.length} combo(s)`:''} · ${money(total)} · ${paymentMethod}`);cart=[];currentQty=1;document.getElementById('qtyDisplay').textContent='1';document.getElementById('clienteNombre').value='';document.getElementById('clienteNombre').removeAttribute('data-client-id');document.getElementById('clienteTelefono').value='';document.getElementById('pagoEfectivo').value='';document.getElementById('vueltoDisplay').textContent='$0';saveLocalData();renderCart();renderSaleProducts();if(typeof renderClients==='function')renderClients();showToast(`💰 Venta registrada: ${money(total)}${offerSummary.combos?.length?' · combo aplicado':''}`,'success')}
function quickSell(id){setSelectedProduct(id);showView('ventas')}
function renderMoves(){const el=document.getElementById('moves');if(!el)return;el.innerHTML=appData.moves.slice(0,300).map(m=>`<tr><td>${new Date(m.date).toLocaleString('es-AR')}</td><td>${escapeHTML(m.product)}</td><td>${m.qty}</td><td>${money(m.total)}</td><td>${escapeHTML(m.cliente||'—')}</td></tr>`).join('')||'<tr><td colspan="5">No hay movimientos</td></tr>'}
function undoLastSale(){if(!appData||!Array.isArray(appData.sales)||!appData.sales.length){showToast('ℹ️ No hay ventas para deshacer','info');return false}const sale=appData.sales[0],items=Array.isArray(sale.items)?sale.items:[];if(!items.length){showToast('⚠️ La última venta no tiene artículos guardados','error');return false}const when=new Date(sale.date).toLocaleString('es-AR'),detail=items.map(i=>`${i.name} ×${i.qty}`).join(', ');if(!confirm(`¿Deshacer la última venta?\n\n${when}\n${detail}\n\nSe devolverán los artículos al stock y se quitará la venta de las estadísticas.`))return false;items.forEach(i=>{const p=findProduct(i.id);if(p)p.stock=Math.max(0,Number(p.stock||0)+Number(i.qty||0))});const saleId=String(sale.id||'');if(saleId){appData.moves=appData.moves.filter(m=>String(m.saleId||'')!==saleId)}else{appData.moves=appData.moves.filter(m=>{if(String(m.date)!==String(sale.date))return true;const item=items.find(i=>Number(i.id)===Number(m.productId)&&Number(i.qty)===Number(m.qty)&&Math.abs(Number(i.total||0)-Number(m.total||0))<0.01);if(!item)return true;if(sale.clientId&&m.clientId&&Number(sale.clientId)!==Number(m.clientId))return true;if(!sale.clientId&&String(sale.cliente||'Sin cliente')!==String(m.cliente||'Sin cliente'))return true;return false})}appData.sales.shift();logActivity('undo','Venta deshecha',`${items.length} artículo(s) · ${money(Number(sale.total||0))}`);saveLocalData();renderAll();showToast(`↩️ Venta deshecha · stock devuelto · ${money(Number(sale.total||0))}`,'success');return true}
function ensureA220UndoButton(){const finish=document.querySelector('button[onclick="finishSale()"]');if(!finish||document.getElementById('a220UndoSaleButton'))return;const b=document.createElement('button');b.id='a220UndoSaleButton';b.className='btn btn-outline btn-block';b.type='button';b.textContent='↩ Deshacer última venta';b.onclick=undoLastSale;finish.insertAdjacentElement('afterend',b)}
function ensureA220OffersModule(){if(document.querySelector('script[data-a220-offers]')||document.querySelector('script[src*="js/offers.js"]'))return;const s=document.createElement('script');s.src='js/offers.js?v=20260907';s.dataset.a220Offers='1';document.body.appendChild(s)}
function ensureA220QuickOffersModule(){if(document.querySelector('script[data-a220-quick-offers]')||document.querySelector('script[src*="js/quick-offers.js"]'))return;const s=document.createElement('script');s.src='js/quick-offers.js?v=20260907';s.dataset.a220QuickOffers='1';document.body.appendChild(s)}
document.addEventListener('DOMContentLoaded',()=>{ensureA220OffersModule();ensureA220QuickOffersModule();setTimeout(ensureA220UndoButton,120);setTimeout(lockSalePrice,150);const qty=document.getElementById('saleQty');if(qty){qty.addEventListener('input',syncSaleQty);qty.addEventListener('change',syncSaleQty)}})
