// A220 Pro - ventas
let cart=[],currentQty=1;
function findProduct(id){return appData.products.find(p=>p.id===Number(id))}
function productSearchText(p){return `${p.name||''} ${p.brand||''} ${p.cat||''} ${p.barcode||''}`.toLowerCase()}
function renderSaleProducts(){const select=document.getElementById('saleProduct');if(!select||!appData)return;const current=select.value;const sorted=[...appData.products].filter(p=>Number(p.stock)>0).sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'es',{sensitivity:'base'}));select.innerHTML='<option value="">Seleccioná...</option>'+sorted.map(p=>`<option value="${p.id}">${escapeHTML(p.name)}${p.brand?` · ${escapeHTML(p.brand)}`:''} · ${money(p.price)} · Stock ${p.stock}</option>`).join('');if(sorted.some(p=>String(p.id)===String(current)))select.value=current;updateSalePreview()}
function setSelectedProduct(id){const p=findProduct(id);if(!p)return;if(Number(p.stock)<=0){showToast('⚠️ Artículo sin stock. Cargá stock desde Artículos.','error');return}const select=document.getElementById('saleProduct');if(select)select.value=String(p.id);document.getElementById('salePrice').value=p.price;updateSalePreview()}
function updateSalePreview(){const p=findProduct(document.getElementById('saleProduct')?.value),box=document.getElementById('productPreview');if(!box)return;if(!p){box.innerHTML='<div class="product-image"><i class="fas fa-box"></i></div><div class="product-info"><div class="product-name">Seleccioná un artículo</div><div class="muted">La compra aparecerá acá</div></div>';return}const src=String(p.image||'').trim(),img=src?`<img src="${escapeHTML(src)}" alt="">`:'<i class="fas fa-box"></i>';box.innerHTML=`<div class="product-image">${img}</div><div class="product-info"><div class="product-name">${escapeHTML(p.name)}</div><div class="muted">${escapeHTML(p.brand||p.cat||'')}</div><div class="product-price">${money(Number(document.getElementById('salePrice')?.value)||p.price)}</div><div class="product-stock">Stock disponible: ${p.stock}</div></div>`}
function renderSearchResults(found){const list=document.getElementById('listaProductos');if(!list)return;list.innerHTML=found.map(p=>`<button class="search-result" onclick="setSelectedProduct(${p.id});document.getElementById('buscarProducto').value='';document.getElementById('listaProductos').style.display='none';document.getElementById('salePrice').focus();"><span><strong>${escapeHTML(p.name)}</strong>${p.brand?`<small>${escapeHTML(p.brand)}</small>`:''}<small>${escapeHTML(p.cat||'General')} · Stock ${p.stock}</small></span><span>${money(p.price)}</span></button>`).join('')||'<div class="empty">No hay artículos con stock.</div>';list.style.display='block'}
function filterSaleProducts(){const input=document.getElementById('buscarProducto'),list=document.getElementById('listaProductos');if(!input||!list||!appData)return;const q=input.value.toLowerCase().trim();if(!q){list.style.display='none';return}const found=appData.products.filter(p=>Number(p.stock)>0&&productSearchText(p).includes(q)).sort((a,b)=>{const aa=productSearchText(a),bb=productSearchText(b),sa=aa.startsWith(q)?0:aa.indexOf(q)>=0?1:2,sb=bb.startsWith(q)?0:bb.indexOf(q)>=0?1:2;return sa-sb||String(a.name).localeCompare(String(b.name),'es',{sensitivity:'base'})}).slice(0,20);renderSearchResults(found)}
function focusProductSearch(){const input=document.getElementById('buscarProducto');input?.focus();if(input?.value)filterSaleProducts()}
function adjustQty(delta){currentQty=Math.max(1,currentQty+delta);document.getElementById('qtyDisplay').textContent=currentQty;document.getElementById('saleQty').value=currentQty}
function addToCart(){const p=findProduct(document.getElementById('saleProduct').value);if(!p){showToast('⚠️ Elegí un artículo','error');return}const qty=Number(document.getElementById('saleQty').value)||1,price=Math.max(0,Number(document.getElementById('salePrice').value)||p.price),existing=cart.find(x=>x.id===p.id),newQty=(existing?.qty||0)+qty;if(Number(p.stock)<=0||newQty>p.stock){showToast('⚠️ Stock insuficiente','error');return}if(existing){existing.qty=newQty;existing.price=price;existing.total=newQty*price}else cart.push({id:p.id,name:p.name,qty,price,total:qty*price});renderCart();showToast('➕ Agregado','success')}
function renderCart(){const el=document.getElementById('cart');if(!el)return;el.innerHTML=cart.map((i,n)=>`<tr><td>${escapeHTML(i.name)}</td><td>${i.qty}</td><td>${money(i.price)}</td><td>${money(i.total)}</td><td><button class="btn btn-xs btn-danger" onclick="removeCart(${n})">×</button></td></tr>`).join('')||'<tr><td colspan="5" class="cart-empty">🛒 Agregá artículos para comenzar</td></tr>';document.getElementById('cartTotal').textContent=money(cart.reduce((a,i)=>a+i.total,0))}
function removeCart(i){cart.splice(i,1);renderCart()}
function calcularVuelto(){const paid=Number(document.getElementById('pagoEfectivo').value)||0,total=cart.reduce((a,i)=>a+i.total,0);document.getElementById('vueltoDisplay').textContent=money(Math.max(0,paid-total))}
function finishSale(){if(!cart.length){showToast('⚠️ El carrito está vacío','error');return}for(const i of cart){const p=findProduct(i.id);if(!p||i.qty>p.stock){showToast(`❌ Stock insuficiente: ${i.name}`,'error');return}}const total=cart.reduce((a,i)=>a+i.total,0),now=new Date().toISOString(),cliente=document.getElementById('clienteNombre').value.trim()||'Sin cliente',telefono=document.getElementById('clienteTelefono').value.trim(),paymentMethod=document.getElementById('paymentMethod')?.value||'cash',paid=paymentMethod==='cash'?(Number(document.getElementById('pagoEfectivo').value)||0):total;if(paymentMethod==='cash'&&paid<total){showToast('⚠️ El efectivo recibido es menor al total','error');return}const sale={id:crypto.randomUUID(),date:now,total,items:structuredClone(cart),cliente,telefono,paid,change:Math.max(0,paid-total),paymentMethod};cart.forEach(i=>{const p=findProduct(i.id);p.stock-=i.qty;appData.moves.unshift({id:crypto.randomUUID(),date:now,product:i.name,productId:i.id,qty:i.qty,total:i.total,cliente})});appData.sales.unshift(sale);logActivity('sale','Venta realizada',`${cart.length} artículo(s) · ${money(total)}`);cart=[];currentQty=1;document.getElementById('qtyDisplay').textContent='1';document.getElementById('clienteNombre').value='';document.getElementById('clienteTelefono').value='';document.getElementById('pagoEfectivo').value='';document.getElementById('vueltoDisplay').textContent='$0';saveLocalData();renderCart();renderSaleProducts();showToast(`💰 Venta registrada: ${money(total)}`,'success');if(typeof a220TryDirectPrintTicket==='function'&&typeof A220_PRINTER_CONFIG!=='undefined'&&A220_PRINTER_CONFIG.autoPrint)a220TryDirectPrintTicket(sale);else if(typeof printLastSale==='function')setTimeout(printLastSale,150)}
function quickSell(id){setSelectedProduct(id);showView('ventas')}
function renderMoves(){const el=document.getElementById('moves');if(!el)return;el.innerHTML=appData.moves.slice(0,300).map(m=>`<tr><td>${new Date(m.date).toLocaleString('es-AR')}</td><td>${escapeHTML(m.product)}</td><td>${m.qty}</td><td>${money(m.total)}</td><td>${escapeHTML(m.cliente||'—')}</td></tr>`).join('')||'<tr><td colspan="5">No hay movimientos</td></tr>'}
