// A220 Pro - historial visual de tickets y edición auditable
let a220TicketHistorySearch='',a220TicketHistoryFilter='all',a220EditingSaleId=null;
function a220TicketClone(v){return typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v))}
function a220TicketFindSale(id){return (appData?.sales||[]).find(s=>String(s.id)===String(id))}
function a220TicketHistoryEnsure(sale){if(!sale)return[];if(!Array.isArray(sale.editHistory))sale.editHistory=[];return sale.editHistory}
function a220TicketDate(s){const d=new Date(s?.date);return Number.isNaN(d.getTime())?'—':d.toLocaleString('es-AR',{dateStyle:'short',timeStyle:'short'})}
function a220TicketLabel(s){return String(s?.cliente||'Sin cliente').trim()||'Sin cliente'}
function a220TicketMatches(s){if(!s)return false;const q=a220TicketHistorySearch.trim().toLowerCase();if(a220TicketHistoryFilter!=='all'){const d=new Date(s.date),now=new Date();if(a220TicketHistoryFilter==='today'&&d.toDateString()!==now.toDateString())return false;if(a220TicketHistoryFilter==='7d'&&(now-d)>7*86400000)return false;if(a220TicketHistoryFilter==='30d'&&(now-d)>30*86400000)return false}if(!q)return true;const hay=[s.id,s.cliente,s.telefono,s.paymentMethod,...(s.items||[]).flatMap(i=>[i.name,i.id])].join(' ').toLowerCase();return hay.includes(q)}
function a220TicketRender(s){const edited=Array.isArray(s.editHistory)&&s.editHistory.length;const items=Array.isArray(s.items)?s.items:[];return `<article class="a220-ticket-card ${edited?'is-edited':''}"><div class="a220-ticket-paper"><div class="a220-ticket-head"><strong>A220</strong><span>${escapeHTML(a220TicketDate(s))}</span></div><div class="a220-ticket-id">TICKET #${escapeHTML(String(s.id||'').slice(-8).toUpperCase())}</div><div class="a220-ticket-lines">${items.map(i=>`<div><span>${escapeHTML(i.name||'Artículo')} ×${Number(i.qty||0)}</span><strong>${money(i.total||0)}</strong></div>`).join('')||'<div><span>Sin artículos</span></div>'}</div><div class="a220-ticket-total"><span>TOTAL</span><strong>${money(s.total||0)}</strong></div><div class="a220-ticket-client"><span>Cliente</span><strong>${escapeHTML(a220TicketLabel(s))}</strong></div><div class="a220-ticket-payment">${escapeHTML(String(s.paymentMethod||'cash'))}${edited?'<span class="a220-edited-badge">✏️ Ticket editado</span>':''}</div></div><div class="a220-ticket-actions"><button class="btn btn-primary" onclick="a220OpenTicketEditor('${escapeHTML(String(s.id))}')">✏️ Editar</button>${edited?`<button class="btn btn-outline" onclick="a220ToggleTicketTimeline('${escapeHTML(String(s.id))}')">🕒 Historial (${s.editHistory.length})</button>`:''}</div><div id="a220Timeline-${escapeHTML(String(s.id))}" class="a220-ticket-timeline hidden"></div></article>`}
function renderTicketHistory(){const root=document.getElementById('tickets');if(!root||!appData)return;const sales=(appData.sales||[]).filter(a220TicketMatches);const list=root.querySelector('#a220TicketList');if(!list)return;list.innerHTML=sales.length?sales.map(a220TicketRender).join(''):'<div class="panel"><div class="muted">No encontramos tickets con esos filtros.</div></div>'}
function a220OpenTicketEditor(id){const sale=a220TicketFindSale(id);if(!sale)return; a220EditingSaleId=String(id);const modal=document.getElementById('a220TicketEditor');if(!modal)return;const clients=Array.isArray(appData.clients)?appData.clients:[];const currentId=Number(sale.clientId)||0;modal.querySelector('#a220TicketEditorContent').innerHTML=`<div class="eyebrow">TICKET #${escapeHTML(String(sale.id||'').slice(-8).toUpperCase())}</div><h2>Editar ticket</h2><div class="a220-editor-summary"><strong>${money(sale.total||0)}</strong><span>${escapeHTML(a220TicketDate(sale))}</span></div><label>Cliente</label><select id="a220TicketClient"><option value="0">Sin cliente</option>${clients.map(c=>`<option value="${Number(c.id)}" ${Number(c.id)===currentId?'selected':''}>${escapeHTML(c.name)}${c.phone?` · ${escapeHTML(c.phone)}`:''}</option>`).join('')}</select><div class="field-note">Por ahora la edición segura del ticket se centra en asignar/corregir el cliente. Los productos, cantidades y precios originales no se pisan.</div><div class="modal-actions"><button class="btn btn-outline" onclick="a220CloseTicketEditor()">Cancelar</button><button class="btn btn-primary" onclick="a220SaveTicketClient()">Guardar cambio</button></div>`;modal.classList.add('active');modal.setAttribute('aria-hidden','false')}
function a220CloseTicketEditor(){const modal=document.getElementById('a220TicketEditor');if(modal){modal.classList.remove('active');modal.setAttribute('aria-hidden','true')}a220EditingSaleId=null}
function a220SaveTicketClient(){const sale=a220TicketFindSale(a220EditingSaleId);const select=document.getElementById('a220TicketClient');if(!sale||!select)return;const oldName=a220TicketLabel(sale),oldId=Number(sale.clientId)||0,newId=Number(select.value)||0,client=(appData.clients||[]).find(c=>Number(c.id)===newId),newName=client?.name||'Sin cliente';if(oldId===newId&&oldName===newName){showToast('ℹ️ No hubo cambios','info');a220CloseTicketEditor();return}const now=new Date().toISOString();a220TicketHistoryEnsure(sale).unshift({id:crypto.randomUUID(),date:now,type:'client',label:'Cliente modificado',before:{clientId:oldId||null,cliente:oldName},after:{clientId:newId||null,cliente:newName}});sale.clientId=newId||null;sale.cliente=newName;if(client?.phone)sale.telefono=client.phone;else if(newId===0)sale.telefono='';(appData.moves||[]).forEach(m=>{if(String(m.saleId)===String(sale.id)){m.clientId=sale.clientId;m.cliente=sale.cliente}});logActivity('ticket-edit','✏️ Ticket editado',`Ticket #${String(sale.id).slice(-8).toUpperCase()} · Cliente: ${oldName} → ${newName}`);saveLocalData();a220CloseTicketEditor();renderTicketHistory();renderAll();showToast('✏️ Ticket actualizado y guardado','success')}
function a220ToggleTicketTimeline(id){const sale=a220TicketFindSale(id),box=document.getElementById(`a220Timeline-${id}`);if(!sale||!box)return;box.classList.toggle('hidden');if(box.classList.contains('hidden'))return;const history=a220TicketHistoryEnsure(sale);box.innerHTML=`<div class="a220-timeline-title">🕒 Línea de tiempo</div><div class="a220-timeline-event"><b>● Venta original</b><span>${escapeHTML(a220TicketDate(sale))}</span><small>Ticket creado · ${escapeHTML(a220TicketLabel(sale))}</small></div>${history.map(h=>`<div class="a220-timeline-event"><b>✏️ ${escapeHTML(h.label||'Modificación')}</b><span>${escapeHTML(a220TicketDate({date:h.date}))}</span><small>${escapeHTML(h.before?.cliente||'Sin cliente')} → <strong>${escapeHTML(h.after?.cliente||'Sin cliente')}</strong></small></div>`).join('')}<div class="a220-timeline-current"><b>ACTUAL</b><span>${escapeHTML(a220TicketLabel(sale))}</span></div>`}
function ensureA220TicketHistoryUI(){if(document.getElementById('tickets'))return;const nav=document.querySelector('nav');const b=document.createElement('button');b.dataset.a220Tickets='1';b.textContent='🧾 Tickets';b.onclick=()=>showView('tickets',b);nav?.insertBefore(b,nav.lastElementChild);const sec=document.createElement('section');sec.id='tickets';sec.className='view';sec.innerHTML='<div class="page-head"><div><div class="eyebrow">HISTORIAL</div><h2>🧾 Tickets</h2><div class="muted">Cada venta como ticket real, con edición e historial.</div></div></div><div class="panel a220-ticket-toolbar"><input id="a220TicketSearch" autocomplete="off" placeholder="🔎 Buscar ticket, cliente o artículo…"><div class="a220-ticket-filters"><button class="range-btn active" data-ticket-filter="all">Todos</button><button class="range-btn" data-ticket-filter="today">Hoy</button><button class="range-btn" data-ticket-filter="7d">7 días</button><button class="range-btn" data-ticket-filter="30d">30 días</button></div></div><div id="a220TicketList" class="a220-ticket-list"></div>';document.querySelector('main')?.appendChild(sec);const modal=document.createElement('div');modal.id='a220TicketEditor';modal.className='modal';modal.setAttribute('aria-hidden','true');modal.innerHTML='<div class="modal-card"><div id="a220TicketEditorContent"></div></div>';document.body.appendChild(modal);document.getElementById('a220TicketSearch')?.addEventListener('input',e=>{a220TicketHistorySearch=e.target.value;renderTicketHistory()});sec.querySelectorAll('[data-ticket-filter]').forEach(btn=>btn.addEventListener('click',()=>{a220TicketHistoryFilter=btn.dataset.ticketFilter;sec.querySelectorAll('[data-ticket-filter]').forEach(x=>x.classList.toggle('active',x===btn));renderTicketHistory()}));renderTicketHistory()}
function showTicketsView(){ensureA220TicketHistoryUI();const b=document.querySelector('nav button[data-a220-tickets]');showView('tickets',b);renderTicketHistory()}
document.addEventListener('DOMContentLoaded',ensureA220TicketHistoryUI);
