// A220 Pro - interfaz, dashboard y arranque
let dashboardRange='today';
function showView(id,btn){
  const target=document.getElementById(id);
  if(!target)return;
  document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));
  target.classList.add('active');
  document.querySelectorAll('nav button').forEach(b=>b.classList.remove('active'));
  if(btn)btn.classList.add('active');
  // La navegación nunca debe quedar bloqueada por un módulo de renderizado.
  try{renderDashboard()}catch(e){console.error('A220 dashboard:',e)}
  try{renderProducts()}catch(e){console.error('A220 products:',e)}
  try{renderSaleProducts()}catch(e){console.error('A220 sales products:',e)}
  try{renderMoves()}catch(e){console.error('A220 movements:',e)}
  try{renderCart()}catch(e){console.error('A220 cart:',e)}
}
function salesInRange(range){const now=new Date(),start=new Date(now),end=new Date(now);if(range==='today'){start.setHours(0,0,0,0)}else if(range==='7d'){start.setDate(start.getDate()-6);start.setHours(0,0,0,0)}else if(range==='30d'){start.setDate(start.getDate()-29);start.setHours(0,0,0,0)}else if(range==='month'){start.setDate(1);start.setHours(0,0,0,0)}end.setHours(23,59,59,999);return appData.sales.filter(s=>{const d=new Date(s.date);return d>=start&&d<=end})}
function renderBarList(id,items,empty='Sin datos'){const el=document.getElementById(id);if(!el)return;if(!items.length){el.innerHTML=`<div class="muted">${empty}</div>`;return}const max=Math.max(...items.map(x=>x.value),1);el.innerHTML=items.map(x=>`<div class="bar-row"><div class="bar-label"><span>${escapeHTML(x.label)}</span><strong>${money(x.value)}</strong></div><div class="bar-track"><i style="width:${Math.max(4,(x.value/max)*100)}%"></i></div></div>`).join('')}
function renderDashboard(){if(!appData)return;const sales=salesInRange(dashboardRange),total=sales.reduce((a,s)=>a+s.total,0),units=sales.reduce((a,s)=>a+s.items.reduce((b,i)=>b+i.qty,0),0),avg=sales.length?total/sales.length:0;const profit=sales.reduce((sum,s)=>sum+s.items.reduce((a,i)=>{const p=findProduct(i.id);return a+(i.price-(p?.cost||0))*i.qty},0),0);document.getElementById('dVentas').textContent=money(total);document.getElementById('dProductos').textContent=appData.products.length;document.getElementById('dBajo').textContent=appData.products.filter(p=>p.stock<=p.minStock).length;document.getElementById('dUnidades').textContent=units;document.getElementById('dTickets').textContent=sales.length;document.getElementById('dTicketProm').textContent=money(avg);document.getElementById('dGanancia').textContent=money(profit);document.getElementById('dashRangeLabel').textContent={today:'Hoy',7d:'Últimos 7 días',30d:'Últimos 30 días',month:'Este mes'}[dashboardRange]||'Período';const hourly=Array.from({length:24},(_,h)=>({label:`${String(h).padStart(2,'0')}h`,value:0}));sales.forEach(s=>{const h=new Date(s.date).getHours();hourly[h].value+=s.total});renderBarList('hourBars',hourly.filter(x=>x.value>0),'No hay ventas en este período');const days={};sales.forEach(s=>{const d=new Date(s.date),key=d.toISOString().slice(0,10);days[key]=(days[key]||0)+s.total});renderBarList('dayBars',Object.entries(days).sort((a,b)=>a[0].localeCompare(b[0])).map(([k,v])=>({label:new Date(k+'T12:00:00').toLocaleDateString('es-AR',{weekday:'short',day:'2-digit',month:'2-digit'}),value:v})),'No hay ventas en este período');const top={};sales.forEach(s=>s.items.forEach(i=>{top[i.name]=(top[i.name]||0)+i.total}));renderBarList('topBars',Object.entries(top).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([label,value])=>({label,value})),'No hay productos vendidos');const low=appData.products.filter(p=>p.stock<=p.minStock);document.getElementById('alertas').innerHTML=low.length?low.map(p=>`<div class="alert-row">⚠️ <strong>${escapeHTML(p.name)}</strong><span>${p.stock} en stock</span></div>`).join(''):'<div class="muted">Sin alertas.</div>'}
function setDashboardRange(range){dashboardRange=range;document.querySelectorAll('.range-btn').forEach(b=>b.classList.toggle('active',b.dataset.range===range));try{renderDashboard()}catch(e){console.error('A220 dashboard:',e)}}
function renderAll(){if(!isLoggedIn||!appData)return;try{renderDashboard()}catch(e){console.error('A220 dashboard:',e)}try{renderProducts()}catch(e){console.error('A220 products:',e)}try{renderSaleProducts()}catch(e){console.error('A220 sales products:',e)}try{renderMoves()}catch(e){console.error('A220 movements:',e)}try{renderCart()}catch(e){console.error('A220 cart:',e)}}
function toggleTheme(){const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem(APP_CONFIG.themeKey,dark?'dark':'light')}
function boot(){const theme=localStorage.getItem(APP_CONFIG.themeKey)||'light';document.documentElement.dataset.theme=theme;loadGitHubConfig();const login=document.getElementById('loginPass');if(login)login.addEventListener('keydown',e=>{if(e.key==='Enter')doLogin()});const search=document.getElementById('buscarProducto');if(search)search.addEventListener('input',filterSaleProducts);const sale=document.getElementById('saleProduct');if(sale)sale.addEventListener('change',updateSalePreview);const price=document.getElementById('salePrice');if(price)price.addEventListener('input',updateSalePreview);const productFilter=document.getElementById('productFilter');if(productFilter)productFilter.addEventListener('input',renderProducts);document.querySelectorAll('.range-btn').forEach(b=>b.addEventListener('click',()=>setDashboardRange(b.dataset.range)));bootAuth()}
document.addEventListener('DOMContentLoaded',boot);